
version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: ep-small-wind-ae4h6ft7.c-2.us-east-2.aws.neon.tech
      DB_PORT: 5432
      DB_USERNAME: neondb_owner
      DB_PASSWORD: npg_8yhekwNsO9GC
      DB_DATABASE: it-rock
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  redis_data:

# services:
#   app:
#     build: .
#     ports:
#       - '3000:3000'
#     environment:
#       DB_HOST: ep-small-wind-ae4h6ft7.c-2.us-east-2.aws.neon.tech
#       DB_PORT: 5432
#       DB_USERNAME: neondb_owner
#       DB_PASSWORD: npg_8yhekwNsO9GC
#       DB_DATABASE: it-rock
#       REDIS_HOST: redis
#       REDIS_PORT: 6379
#     depends_on:
#       db:
#         condition: service_healthy
#       redis:
#         condition: service_healthy

#   db:
#     image: postgres:15-alpine
#     environment:
#       POSTGRES_USER: neondb_owner
#       POSTGRES_PASSWORD: npg_8yhekwNsO9GC
#       POSTGRES_DB: it-rock
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

#   redis:
#     image: redis:7-alpine
#     ports:
#       - "6379:6379"
#     volumes:
#       - redis_data:/data
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

# volumes:
#   postgres_data:
#   redis_data: